CREATE TABLE Homework(
	HomeworkID INT IDENTITY(1,1) PRIMARY KEY,
	CourseID INT FOREIGN KEY REFERENCES Course ON DELETE CASCADE,
	TopicName CHAR(25) NOT NULL,
	Content VARCHAR(200) NOT NULL,
	Deadline DATETIME
)